/** UI copy (pt-BR) for the landing + auth surfaces. English-named keys. */
export const landingCopy = {
	brandPrefix: "Re",
	brandSuffix: "Serve",
	navLogin: "Entrar",
	navRegister: "Cadastrar",
	heroEyebrow: "Reservas inteligentes",
	heroTitleLine1: "A sua mesa",
	heroTitleLine2Prefix: "te ",
	heroTitleEmphasis: "espera",
	heroSubtitle:
		"Reserve mesas nos melhores restaurantes da cidade em segundos. Experiências gastronômicas inesquecíveis a um clique.",
	heroLoginClient: "Entrar como cliente",
	heroRestaurantArea: "Área do restaurante",
	stats: [
		{ value: "1.2k+", label: "Restaurantes" },
		{ value: "48k+", label: "Reservas feitas" },
		{ value: "4.9★", label: "Avaliação média" },
	],
	footerCopyright: "© 2026 ReServe. Todos os direitos reservados.",
	footerCredits: "Projeto Integrador · Grupo 41 · Senac",
} as const;

export const authCopy = {
	loginClientTitle: "Entrar como cliente",
	loginRestaurantTitle: "Área do restaurante",
	registerTitle: "Criar conta",
	emailLabel: "Email",
	corporateEmailLabel: "Email corporativo",
	passwordLabel: "Senha",
	emailPlaceholder: "seu@email.com",
	corporateEmailPlaceholder: "contato@restaurante.com",
	passwordPlaceholder: "••••••••",
	loginClientSubmit: "Entrar",
	loginRestaurantSubmit: "Acessar painel",
	noAccount: "Não tem conta?",
	newRestaurant: "Novo restaurante?",
	createFreeAccount: "Criar conta grátis",
	registerRestaurantCta: "Cadastrar restaurante",
	tabClient: "👤 Cliente",
	tabRestaurant: "🍽️ Restaurante",
	fullNameLabel: "Nome completo",
	fullNamePlaceholder: "João Silva",
	phoneLabel: "Telefone",
	phonePlaceholderClient: "(11) 9 0000-0000",
	phonePlaceholderRestaurant: "(11) 3000-0000",
	restaurantNameLabel: "Nome do restaurante",
	restaurantNamePlaceholder: "Cantina Bella",
	addressLabel: "Endereço completo",
	addressPlaceholder: "Rua das Flores, 123 — São Paulo, SP",
	bioLabel: "Bio / Descrição",
	bioPlaceholder: "Conte um pouco sobre seu restaurante…",
	registerClientSubmit: "Criar minha conta",
	registerRestaurantSubmit: "Cadastrar restaurante",
	loginSuccess: "Bem-vindo de volta!",
	registerClientSuccess: "Conta criada com sucesso!",
	registerRestaurantSuccess:
		"Restaurante cadastrado! Vamos configurar seu espaço.",
	logoutSuccess: "Sessão encerrada.",
	genericError: "Algo deu errado. Tente novamente.",
} as const;
